apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace : demo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/redis"
  claimRef:
      name: data-volume
      namespace: demo